# Generated by Django 3.1.4 on 2020-12-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='media/products'),
        ),
        migrations.AlterField(
            model_name='recentwork',
            name='image',
            field=models.ImageField(upload_to='media/recent'),
        ),
    ]
